# Generated by Django 5.2.17 on 2026-09-27 09:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, db_table='auth_user_groups', help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, db_table='auth_user_user_permissions', help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=180, verbose_name='توضیح')),
                ('icon_bg', models.CharField(default='bg-teal-100 text-teal-700', max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='شهر')),
                ('province', models.CharField(max_length=64, verbose_name='استان')),
                ('is_featured', models.BooleanField(default=False, verbose_name='شهر پربازدید')),
                ('featured_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['province', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'صاحب زمین'), ('worker', 'کارگر')], max_length=10, verbose_name='نقش')),
                ('phone', models.CharField(max_length=11, verbose_name='موبایل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='marketplace.User')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام خدمت')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=220, verbose_name='توضیح')),
                ('base_price', models.PositiveIntegerField(default=0, verbose_name='شروع قیمت روزانه')),
                ('gradient', models.CharField(blank=True, max_length=80)),
                ('is_popular', models.BooleanField(default=False, verbose_name='پرتقاضا')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marketplace.category', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس زمین')),
                ('work_date', models.DateField(verbose_name='تاریخ مراجعه')),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مساحت (هکتار)')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('wage', models.PositiveIntegerField(default=0, verbose_name='دستمزد روزانه در زمان رزرو')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'پذیرفته شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده'), ('done', 'انجام شده')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='marketplace.User', verbose_name='صاحب زمین')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.city', verbose_name='شهر')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='marketplace.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='درباره تجربه کاری')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)], verbose_name='سابقه (سال)')),
                ('daily_wage', models.PositiveIntegerField(default=0, verbose_name='دستمزد روزانه (تومان)')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='امتیاز')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظر')),
                ('jobs_done', models.PositiveIntegerField(default=0, verbose_name='کارهای انجام\u200cشده')),
                ('is_verified', models.BooleanField(default=False, verbose_name='هویت تأیید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='آماده دریافت کار')),
                ('cities', models.ManyToManyField(blank=True, related_name='workers', to='marketplace.city', verbose_name='محل کار')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='marketplace.profile', verbose_name='کاربر')),
                ('services', models.ManyToManyField(blank=True, related_name='workers', to='marketplace.service', verbose_name='حوزه کاری')),
            ],
            options={
                'verbose_name': 'پروفایل کارگر',
                'verbose_name_plural': 'پروفایل کارگران',
                'ordering': ['-rating', '-jobs_done'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.workerprofile')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='marketplace.workerprofile', verbose_name='کارگر'),
        ),
    ]
