# Generated by Django 5.2.17 on 2026-09-27 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید ادمین'),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobs', to=settings.AUTH_USER_MODEL, verbose_name='ادمین تأییدکننده'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اعلام انجام'),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس زمین'),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='marketplace.city', verbose_name='شهر زمین'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پذیرش'), ('confirmed', 'پذیرفته شده'), ('reported', 'اعلام انجام، منتظر ادمین'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده'), ('done', 'انجام تأیید شد')], default='pending', max_length=12, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('farmer', 'صاحب زمین'), ('worker', 'کارگر'), ('admin', 'ادمین')], max_length=10, verbose_name='نقش'),
        ),
    ]
