# Generated by Django 5.2.17 on 2026-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_booking_confirmed_at_booking_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='farm_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی زمین'),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی زمین'),
        ),
    ]
